give @s assy:zombie_spell
give @s assy:catapult_sword
give @s assy:wooden_katana
give @s assy:stone_katana
give @s assy:cavemen_bat
give @s assy:magic_wand
give @s assy:iron_man_landers
give @s assy:destroyer
give @s assy:iron_hammer
give @s assy:katana
give @s assy:horse_teleport
give @s assy:big_snowball
give @s assy:ice_blade
give @s assy:falcon_bomb
give @s assy:hunter_crossbow
give @s assy:hard_plank
give @s assy:disk_generator
give @s assy:ice_boulder
give @s assy:explosive_disk
give @s assy:dagger
give @s assy:infinity_gauntlet
give @s assy:power_rifle
give @s assy:baton
give @s assy:hulk_hand
give @s assy:hulk_body
give @s assy:hulk_feet
give @s assy:leather_helmet
give @s assy:golden_leggings
give @s assy:superboots
give @s assy:leather_tunic
give @s assy:leather_leggings
give @s assy:camo_vest
give @s assy:golden_chestplate
give @s assy:camo_pants
give @s assy:speed_one
give @s assy:speed_two
give @s assy:speed_three
give @s assy:soul_stone
give @s assy:speed_five
give @s assy:speed_sixteen
give @s assy:spiderman_webfiller
give @s assy:ultimate_trident
give @s assy:upgraded_trident
give @s assy:spiderman_web_grappler
give @s assy:spiderman_web_trapper
give @s assy:poison_bomb
give @s assy:buffed_disk_generator
give @s assy:buffed_ice_boulder
give @s assy:buffed_catapult
give @s assy:zom_disk_generator
give @s assy:hell_katana
give @s assy:golden_helmet
give @s assy:poison_katana
give @s assy:packed_ice_blade
give @s assy:master_katana
give @s assy:buffed_shuriken
give @s assy:buffed_disk
give @s assy:cavemen_fury
give @s assy:mystery_box
give @s assy:iron_katana
give @s assy:golden_katana
give @s assy:diamond_katana
give @s assy:netherite_katana
give @s assy:ghost_hand
give @s assy:reaper_hand
give @s assy:buffed_crossbow
give @s assy:death_trident
give @s assy:splashing_needles
give @s assy:zombie_slayer
give @s assy:pearl_generator
give @s assy:packed_rifle
give @s assy:normal_trident
give @s assy:wind_charger
give @s assy:assy_vest
give @s assy:lighting
give @s assy:reality_disk
give @s assy:dying_block
give @s assy:magic_sword
give @s assy:vampirefeast
give @s assy:demon_sword
give @s assy:ghostspeed
give @s assy:devil_sword
give @s assy:buffed_hammer
give @s assy:potion_summoner
give @s assy:shuriken
give @s assy:ice_spell
give @s assy:revolver
give @s assy:nausea_spell
give @s assy:laser_rifle
give @s assy:shotgun
give @s assy:buffed_revolver
give @s assy:upgrader_template
give @s assy:buffed_shotgun
