summon evocation_fang ~4 ~ ~4
summon evocation_fang ~4 ~ ~
summon evocation_fang ~ ~ ~4
summon evocation_fang ~-4 ~ ~-4
summon evocation_fang ~4 ~ ~-4
summon evocation_fang ~ ~ ~-4
summon evocation_fang ~-4 ~ ~
summon evocation_fang ~-4 ~ ~4
summon evocation_fang ~-5 ~ ~5
summon evocation_fang ~5 ~ ~-5
summon evocation_fang ~ ~ ~-5
summon evocation_fang ~-5 ~ ~
summon evocation_fang ~-5 ~ ~-5
summon evocation_fang ~5 ~ ~
summon evocation_fang ~ ~ ~5
summon evocation_fang ~5 ~ ~5
summon evocation_fang ~ ~ ~6
summon evocation_fang ~6 ~ ~
summon evocation_fang ~6 ~ ~6
summon evocation_fang ~-6 ~ ~
summon evocation_fang ~ ~ ~-6
summon evocation_fang ~-6 ~ ~-6
summon evocation_fang ~6 ~ ~-6
summon evocation_fang ~-6 ~ ~6